# -*- coding: utf-8 -*-
"""Best route

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zrv0Tks_38al4oD7hiJWcWbUstIe70-8
"""

import pandas as pd
import heapq
import time
df = pd.read_csv('Flight_Data.csv')