# -*- coding: utf-8 -*-
"""Best route A*.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tIWGGVIJur5PUyFiH7TsEpCW-hUQ2Tp-
"""

import heapq
import time
import pandas as pd
df = pd.read_csv('Flight_Data.csv')