# -*- coding: utf-8 -*-
"""Best route A*.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tIWGGVIJur5PUyFiH7TsEpCW-hUQ2Tp-
"""

import heapq
import time
import pandas as pd
df = pd.read_csv('Flight_Data.csv')
Start = time.time()
graph = {}
graphD = {}
graphF = {}
graphA = {}
Country = {}
City = {}
Latitude = {}
Longitude = {}
Altitude = {}
for _, row in df.iterrows():
    weight = row.Price
    Distance = row.Distance
    FlyTime = row.FlyTime
    Airline = row.Airline
    Country[row.DestinationAirport] = row.DestinationAirport_Country
    City[row.DestinationAirport] = row.DestinationAirport_City
    Latitude[row.DestinationAirport] = row.DestinationAirport_Latitude
    Longitude[row.DestinationAirport] = row.DestinationAirport_Longitude
    Altitude[row.DestinationAirport] = row.DestinationAirport_Altitude
    graph.setdefault(row.SourceAirport, {})
    graphD.setdefault(row.SourceAirport, {})
    graphF.setdefault(row.SourceAirport, {})
    graphA.setdefault(row.SourceAirport, {})
    graph.setdefault(row.DestinationAirport, {})
    graphD.setdefault(row.DestinationAirport, {})
    graphF.setdefault(row.DestinationAirport, {})
    graphA.setdefault(row.DestinationAirport, {})
    graph[row.SourceAirport][row.DestinationAirport] = weight
    graphD[row.SourceAirport][row.DestinationAirport] = Distance
    graphF[row.SourceAirport][row.DestinationAirport] = FlyTime
    graphA[row.SourceAirport][row.DestinationAirport]= Airline
Path = astar(graphD, graph, graphF, graphA, 'Imam Khomeini International Airport', 'Raleigh Durham International Airport', Latitude, Longitude, Altitude)